
package cc.hansam.java.net.ws.odb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSServiceImplService", targetNamespace = "http://support.ws.integration.server.odb.product.uinnova.com/", wsdlLocation = "http://192.168.1.124:1533/ws/shi?wsdl")
public class WSServiceImplService
    extends Service
{

    private final static URL WSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WSSERVICEIMPLSERVICE_QNAME = new QName("http://support.ws.integration.server.odb.product.uinnova.com/", "WSServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.124:1533/ws/shi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WSServiceImplService() {
        super(__getWsdlLocation(), WSSERVICEIMPLSERVICE_QNAME);
    }

    public WSServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICEIMPLSERVICE_QNAME);
    }

    public WSServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSServiceImpl
     */
    @WebEndpoint(name = "WSServiceImplPort")
    public WSServiceImpl getWSServiceImplPort() {
        return super.getPort(new QName("http://support.ws.integration.server.odb.product.uinnova.com/", "WSServiceImplPort"), WSServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSServiceImpl
     */
    @WebEndpoint(name = "WSServiceImplPort")
    public WSServiceImpl getWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://support.ws.integration.server.odb.product.uinnova.com/", "WSServiceImplPort"), WSServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
