
package cc.hansam.java.net.ws.odb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSServiceImpl", targetNamespace = "http://support.ws.integration.server.odb.product.uinnova.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "call", targetNamespace = "http://support.ws.integration.server.odb.product.uinnova.com/", className = "cc.hansam.java.net.ws.odb.Call")
    @ResponseWrapper(localName = "callResponse", targetNamespace = "http://support.ws.integration.server.odb.product.uinnova.com/", className = "cc.hansam.java.net.ws.odb.CallResponse")
    @Action(input = "http://support.ws.integration.server.odb.product.uinnova.com/WSServiceImpl/callRequest", output = "http://support.ws.integration.server.odb.product.uinnova.com/WSServiceImpl/callResponse")
    public String call(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
